// Login
POST http://localhost:8090/auth
Content-Type: application/json
Charset: utf-8

{
	"username":"wang",
	"password":"wang1234"
}

###
//Projects
GET http://localhost:8090/projects/?enabled=true&archived=false
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3YW5nIiwiY3JlYXRlZCI6MTQ5MjQ5NDY1MTQ4OSwiZXhwIjoxNDkzMDk5NDUxfQ.7KqheQW14zjW2cFEbWUnvSz5RXzItxwjVTZ3fa2K3rjkU4anN-A4Wu0kBaJ_adHNY5XRlygVfNQOfPTaQBgq2w
userId: 58f5a904edc76ab0e033cfc3

###
// Pageable
GET http://localhost:8090/projects/?page=0&size=3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ3YW5nIiwiY3JlYXRlZCI6MTQ5MjQ5NDY1MTQ4OSwiZXhwIjoxNDkzMDk5NDUxfQ.7KqheQW14zjW2cFEbWUnvSz5RXzItxwjVTZ3fa2K3rjkU4anN-A4Wu0kBaJ_adHNY5XRlygVfNQOfPTaQBgq2w
userId: 58f5a904edc76ab0e033cfc3

###
//Tasks
GET http://localhost:3000/taskLists?_embed=tasks&projectId=p0001

###
GET https://taskmgr.wilddogio.com/projects.json?orderBy="enabled"&equalTo=true&auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0OTMzNzczMzksInVzZXJfaWQiOiI0N2RhYTQyYzczNmQ4MTZiY2IzZGMyMmFhYmRiIiwiaXNzIjoiaHR0cHM6Ly90YXNrbWdyLndpbGRkb2dpby5jb20iLCJuYW1lIjoiIiwicGljdHVyZSI6IiIsImVtYWlsIjoid2FuZ0AxNjMuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV9udW1iZXIiOiIiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOmZhbHNlLCJ3aWxkZG9nIjp7ImlkZW50aXRpZXMiOnsicGFzc3dvcmQiOlsid2FuZ0AxNjMuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiZXhwIjoxNDk4MjE1NzM5fQ.gXnf90cq_KSqQ75XfpmUBq_jpksLi4pUvcV4LPIikx4

###
POST https://taskmgr.wilddogio.com/projects.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0OTMzNzczMzksInVzZXJfaWQiOiI0N2RhYTQyYzczNmQ4MTZiY2IzZGMyMmFhYmRiIiwiaXNzIjoiaHR0cHM6Ly90YXNrbWdyLndpbGRkb2dpby5jb20iLCJuYW1lIjoiIiwicGljdHVyZSI6IiIsImVtYWlsIjoid2FuZ0AxNjMuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV9udW1iZXIiOiIiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOmZhbHNlLCJ3aWxkZG9nIjp7ImlkZW50aXRpZXMiOnsicGFzc3dvcmQiOlsid2FuZ0AxNjMuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiZXhwIjoxNDk4MjE1NzM5fQ.gXnf90cq_KSqQ75XfpmUBq_jpksLi4pUvcV4LPIikx4
Content-Type: application/json
Charset: utf-8

{
	"name": "CMRead",
	"desc": "The android app for reading books"
}

###
OPTIONS https://taskmgr.wilddogio.com/projects.json?auth=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2IjoxLCJpYXQiOjE0OTM3MDI4ODIsInVzZXJfaWQiOiI0N2RhYTQyYzczNmQ4MTZiY2IzZGMyMmFhYmRiIiwiaXNzIjoiaHR0cHM6Ly90YXNrbWdyLndpbGRkb2dpby5jb20iLCJuYW1lIjoiIiwicGljdHVyZSI6IiIsImVtYWlsIjoid2FuZ0AxNjMuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV9udW1iZXIiOiIiLCJwaG9uZV9udW1iZXJfdmVyaWZpZWQiOmZhbHNlLCJ3aWxkZG9nIjp7ImlkZW50aXRpZXMiOnsicGFzc3dvcmQiOlsid2FuZ0AxNjMuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifSwiZXhwIjoxNDk4NTQxMjgyfQ.Rwf2WuFLaOzg13QMbXJlYefH0rxeRFh7TjOQxgBjajs HTTP/1.1
Access-Control-Request-Method: POST
Access-Control-Request-Headers: Content-Type
Origin: localhost
Host: taskmgr.wilddogio.com